name: Build and Push Docker Image

on:
  push:
    branches:
      - cloud-test
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./
        file: Dockerfile
        push: true
        tags: mandycv/strapi:nodejs-app

        
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures deployment only runs after the build job completes successfully

    steps:
      - name: Deploy Docker Container on Ubuntu Server
        run: |
            << EOF
            # Stop and remove the existing container if it's running
            docker stop nodejs-app-container || true
            docker rm nodejs-app-container || true

            # Pull the latest image from Docker Hub
            docker pull mandycv/strapi:nodejs-app
            mandycv/strapi:nodejs-app
            EOF
